AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
    CustomerManagementLambdaLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: customer-management-backend-api-util-layer
            Description: customerManagement-backend-api
            ContentUri: lambdaLayer/nodejs.zip
            CompatibleRuntimes:
                - nodejs18.x

    CustomerManagement:
        DependsOn: CustomerManagementLambdaLayer
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: index.handler
            Runtime: nodejs18.x
            CodeUri: src/
            FunctionName: customerManagement-backend-api
            Description: customer management backend api
            MemorySize: 256
            Timeout: 30
            Layers:
                - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:customer-management-backend-api-util-layer:1
            Environment:
                Variables:
                    FRONT_END_ORIGIN_URI: ''
                    DATABASE_URL: ''
            FunctionUrlConfig:
                AuthType: NONE

    CustomerManagementLogGroup:
        Type: 'AWS::Logs::LogGroup'
        Properties:
            LogGroupName: '/aws/lambda/customerManagement-backend-api'
            RetentionInDays: 365
