AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
    MyLambdaFunction:
        Type: 'AWS::Serverless::Function'
        Properties:
            Handler: index.handler
            Runtime: nodejs18.x
            CodeUri: src/
            Description: A simple AWS Lambda function example.
            MemorySize: 128
            Timeout: 10
            Environment:
                Variables:
                    LOG_LEVEL: 'INFO'

    MyLogGroup:
        Type: 'AWS::Logs::LogGroup'
        Properties:
            LogGroupName: '/aws/lambda/my_lambda_function'
            RetentionInDays: 14
