version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "customer-management"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
template_file = "customerManagementSamTemplate.yaml"
